# -*- coding: utf-8 -*-
"""3_Regresion_venta_videojuegos_XGBoost.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mBcnov8vQd-_PL7CIOkqeYEI1ir0hSoI

#  Regresion: Predicción de ventas en una tienda de videojuegos
1. Preparación de Datos
2. División de los datos
3. Aprendizaje del Modelo
4. Evaluación del Modelo: MSE, RMSE, MAE, MAPE
5. Guardamos el modelo
"""

#Importamos librerías básicas
import pandas as pd # manipulacion dataframes
import numpy as np  # matrices y vectores
import matplotlib.pyplot as plt #gráfica

"""# 1. Preparación de Datos

"""

#Cargamos los datos
data = pd.read_csv("videojuegos.csv")
data.head()

#Correccion de tipos de datos
data['videojuego']=data['videojuego'].astype('category')
data['Sexo']=data['Sexo'].astype('category')
data['Plataforma']=data['Plataforma'].astype('category')

data.info()

data.info()

"""**Perfilado de datos**"""

!pip install ydata-profiling

from ydata_profiling import ProfileReport

profile_data=ProfileReport(data, minimal=True) # minimal=True
profile_data

#Guardamos en html el perfilado de datos
profile_data.to_file(output_file="output.html")

"""**regresion** no se aplicca label encode, solo en clasificación.

y no se aplica balanceo, es solo en clasificación

"""

#Creamos variables dummy para convertir  las categorías a números
data = pd.get_dummies(data, columns=['videojuego', 'Plataforma'], drop_first=False, dtype=int)
data = pd.get_dummies(data, columns=['Sexo', 'Consumidor_habitual'], drop_first=True, dtype=int)
data.head()

"""# 2. División 70-30

"""

#División 70-30
from sklearn.model_selection import train_test_split
X = data.drop("Presupuesto para invertir", axis = 1) # Variables predictoras
Y = data['Presupuesto para invertir'] #Variable objetivo
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, stratify=None) #la estratificado se usa cuando la variable objetivo tiene categorias
Y_train.plot(kind='box') #la variable objetivo de entrenamiento

# Variable objetivo del 30% - histograma
Y_test.plot(kind='hist')

"""# 3. Aprendizaje  70% y Evaluación 30%"""

#Dataframe para comparar los resultados
medidas= pd.DataFrame(index=['mse','rmse','mae','mape','max']) # rmse raiz, mae absoluto , mape conceptual max peor

"""# Arbol de Regresión
-No se normaliza porque pierden explicabilidad

**Hiperparametros del árbol**: indice de informacion, cantidad de registros por hoja, y su profundidad

en las **hojas de clasificacion** se ven los nombres/categorías

en las **hojas de regresion** deben estar valores de prediccion
"""

#Creación del modelo con el conjunto de entrenamiento
from sklearn.tree import DecisionTreeRegressor
model_Tree = DecisionTreeRegressor(criterion='squared_error', min_samples_leaf=2, max_depth=8)
model_Tree.fit(X_train, Y_train)#70% entrenamiento

#Graficar el árbol
from sklearn.tree import plot_tree
nombres_variables=X_train.columns.values
plt.figure(figsize=(20,20))
plot_tree(model_Tree, feature_names=nombres_variables, filled=True,fontsize=8)
plt.show()

#Evaluación del árbol 30%
from sklearn import metrics
Y_pred = model_Tree.predict(X_test) #30%

#Medidas de evaluación en regresión
mse = metrics.mean_squared_error(Y_test,Y_pred) #No es intepretable
rmse = np.sqrt(mse) #Si es intepretable
mae= metrics.mean_absolute_error(Y_test,Y_pred) #Si es intepretable
mape=metrics.mean_absolute_percentage_error(Y_test,Y_pred) #Verificar si la objetivo es 0
max=metrics.max_error(Y_test,Y_pred)
medidas['Arbol']=[mse, rmse, mae, mape,max]
medidas

#Gráfica Valor Real vs Predicción
plt.scatter(Y_test, Y_pred)
plt.plot([Y_test.min(), Y_test.max()], [Y_test.min(), Y_test.max()],'k--', color = 'black', lw=2)
plt.xlabel('Valor real')
plt.ylabel('Valor del modelo')
plt.title('Valor Real vs Predicción Tree')
plt.show() # Mostrar la grafica luego de que ya se definio todos los elementos

"""# Random Forest para Regresión
- No se normaliza
"""

#Random Forest

from sklearn.ensemble import RandomForestRegressor



model_rf= RandomForestRegressor(n_estimators=300,  max_samples=0.9, criterion='squared_error',

                              max_depth=10, min_samples_leaf=2)

model_rf.fit(X_train, Y_train) #70%

#evaluacion , con la grafica de valor real vs prediciccion
#Evaluación de Random
from sklearn import metrics

Y_pred = model_rf.predict(X_test) #30%

#Medidas de error
mse = metrics.mean_squared_error(Y_test,Y_pred)
rmse = np.sqrt(mse)
mae= metrics.mean_absolute_error(Y_test,Y_pred)
mape=metrics.mean_absolute_percentage_error(Y_test,Y_pred)
max=metrics.max_error(Y_test,Y_pred)
medidas['RF']=[mse, rmse, mae, mape,max]
print(medidas)

#Gráfica Valor Real vs Predicción
plt.scatter(Y_test, Y_pred)
plt.plot([Y_test.min(), Y_test.max()], [Y_test.min(), Y_test.max()],'k--', color = 'black', lw=2)
plt.xlabel('Valor real')
plt.ylabel('Valor del modelo')
plt.title('Valor Real vs Predicción Random')
plt.show()

#grafica de la variable mas relevante
importances = model_rf.feature_importances_
feature_names = X_train.columns
forest_importances = pd.Series(importances, index=feature_names)

fig, ax = plt.subplots()
forest_importances.sort_values(ascending=False).plot.bar(ax=ax)
ax.set_title("Importancia de las características (Random Forest)")
ax.set_ylabel("Importancia Media según el criterion")
fig.tight_layout()
plt.show()

"""# XGBoost para Regresión
- No se normaliza (igual que los árboles, es un modelo basado en splits)
- Si no está instalado en tu entorno: `!pip install xgboost`
"""

#XGBoost
from xgboost import XGBRegressor

model_xgb = XGBRegressor(n_estimators=300, max_depth=6, learning_rate=0.1,
                          objective='reg:squarederror', random_state=42)

model_xgb.fit(X_train, Y_train) #70%

#Evaluación de XGBoost
from sklearn import metrics

Y_pred = model_xgb.predict(X_test) #30%

#Medidas de error
mse = metrics.mean_squared_error(Y_test,Y_pred)
rmse = np.sqrt(mse)
mae= metrics.mean_absolute_error(Y_test,Y_pred)
mape=metrics.mean_absolute_percentage_error(Y_test,Y_pred)
max=metrics.max_error(Y_test,Y_pred)
medidas['XGBoost']=[mse, rmse, mae, mape,max]
print(medidas)

#Gráfica Valor Real vs Predicción
plt.scatter(Y_test, Y_pred)
plt.plot([Y_test.min(), Y_test.max()], [Y_test.min(), Y_test.max()],'k--', color = 'black', lw=2)
plt.xlabel('Valor real')
plt.ylabel('Valor del modelo')
plt.title('Valor Real vs Predicción XGBoost')
plt.show()

#Grafica de la variable mas relevante (XGBoost)
importances = model_xgb.feature_importances_
feature_names = X_train.columns
xgb_importances = pd.Series(importances, index=feature_names)

fig, ax = plt.subplots()
xgb_importances.sort_values(ascending=False).plot.bar(ax=ax)
ax.set_title("Importancia de las características (XGBoost)")
ax.set_ylabel("Importancia (gain)")
fig.tight_layout()
plt.show()

"""# KNN para Regresión
* Normalización de las var numéricas
"""

#Normalizacion de las variables numéricas (las dummies no se normalizan)
from sklearn.preprocessing import MinMaxScaler

min_max_scaler = MinMaxScaler()

variables_numericas=['Edad'] #Predictoras numéricas

#Ajuste de los parametros sobre 100% de los datos (data): max - min
min_max_scaler.fit(data[variables_numericas])

#Se aplica la normalización a 70%  y 30%
X_train[variables_numericas]= min_max_scaler.transform(X_train[variables_numericas]) #70%
X_test[variables_numericas]= min_max_scaler.transform(X_test[variables_numericas]) #30%
X_train.head()



"""# Red Neuronal para Regresión
- Normalizar
"""



"""# SVM para Regresión - SVR

-Normalizar
"""

#SVR
#Kernel='linear', 'poly', 'rbf', 'sigmoid', 'precomputed'

"""# 4. Guardamos el modelo seleccionado

"""

medidas

"""**Selecion del modelo:**
1. Calidad de los modelos: Knn, NN y Tree desempeño parecido en recall
2. Complejidad computacional: Tree mas liviano computacionalmente

**Selección de modelo:**
"""

modelo_final=model_NN

"""Se entrena modelo final con 100% de los datos (X,Y)"""

# Si selecciona Knn, NN, SVM, Reg -> se debe normalzar X (100% de los datos)
# Si selecciona Tree no se normaliza y se comenta la siguiente línea
X[variables_numericas]= min_max_scaler.transform(X[variables_numericas])

#Entrenamos modelo final
modelo_final.fit(X, Y) #100%

import pickle
filename = 'modelo-reg.pkl'
variables=X.columns._values
pickle.dump([modelo_final, min_max_scaler,variables], open(filename, 'wb'))